const currencySymbolMap = {
    USD: "$",
    EUR: "€",
    JPY: "¥",
    GBP: "£",
    AUD: "A$",
    CAD: "C$",
    CHF: "CHF",
    CNY: "CN¥",
    SEK: "kr",
    NZD: "NZ$",
    KRW: "₩",
    SGD: "S$",
    NOK: "kr",
    MXN: "MX$",
    INR: "₹",
    RUB: "₽",
    ZAR: "R",
    BRL: "R$",
    TRY: "₺",
    HKD: "HK$",
    PLN: "zł",
    DKK: "kr",
    THB: "฿",
    IDR: "Rp",
    HUF: "Ft",
    CZK: "Kč",
    ISK: "kr",
    PHP: "₱",
    MYR: "RM",
    HRK: "kn",
    RON: "lei",
    ILS: "₪",
    CLP: "CLP$",
    COP: "COL$",
    ARS: "AR$",
    PEN: "S/.",
    VND: "₫",
    UAH: "₴",
    AED: "د.إ",
    SAR: "ر.س",
    QAR: "ر.ق",
    NGN: "₦",
    BDT: "৳",
    LKR: "රු",
    KES: "Ksh",
    EGP: "£",
    MAD: "د.م.",
    PKR: "₨",
    IQD: "ع.د",
    DZD: "د.ج",
    TWD: "NT$",
    KWD: "د.ك",
    CRC: "₡",
    PYG: "₲",
    BHD: "ب.د",
    OMR: "ر.ع.",
    JOD: "د.ا",
    LBP: "ل.ل",
    TZS: "TSh",
    LYD: "ل.د",
    UYU: "$U",
    ETB: "Br",
    GHS: "₵",
    YER: "﷼",
    NPR: "रू",
    BOB: "Bs",
    SDG: "ج.س.",
    TND: "د.ت",
    DOP: "RD$",
    KZT: "₸",
    UZS: "so'm",
    RSD: "дин.",
    MKD: "ден",
    CUC: "CUC$",
    XAF: "FCFA",
    XOF: "CFA",
    XCD: "EC$",
    XPF: "₣",
    XAU: "oz t",
    XAG: "oz",
    XPT: "oz t",
    XPD: "oz t",
  };
  
  export default currencySymbolMap;
  